#!/usr/bin/env python
#
# 0rk v0.1.2
#
# Art & Words from <http://jvns.ca/>
#
# Code by <http://rancidbacon.com/>
#
# See: <https://twitter.com/starakaj/status/992124188021460992>
#
# This is a proof-of-concept which currently only works on MmacOSX.
#
# (Proof-of-concept only because I want to check @b0rk is okay with it. :) )
#

import os
import sys
import urllib2
import hashlib
import subprocess

# Note: There are SVG files available also.

SUBJECTS = {
    'pipes': {'img_url': 'https://drawings.jvns.ca/drawings/pipes.png', 'page_url': 'https://drawings.jvns.ca/pipes/'},
    'man': {'img_url': 'https://drawings.jvns.ca/drawings/man.png',  'page_url': 'https://drawings.jvns.ca/man/'},
    }


CONFIG_DIR_PATH = os.path.realpath(os.path.expanduser("~/.0rk/"))
CACHE_SUBDIR_NAME = "cache"
CACHE_DIR_PATH = os.path.join(CONFIG_DIR_PATH, CACHE_SUBDIR_NAME)


def get_cached_file_path(the_subject):
    """
    """
    if not os.path.exists(CONFIG_DIR_PATH):
        print "Creating configuration/cache directory: %s" % CONFIG_DIR_PATH
        os.mkdir(CONFIG_DIR_PATH)

    if not os.path.exists(CACHE_DIR_PATH):
        os.mkdir(CACHE_DIR_PATH)

    the_url = SUBJECTS[the_subject]['img_url']
    cached_img_file_name = "%s.png" % hashlib.sha1(the_url).hexdigest()

    cached_img_file_path = os.path.join(CACHE_DIR_PATH, cached_img_file_name)

    if not os.path.exists(cached_img_file_path):
        open(cached_img_file_path, "wb").write(urllib2.urlopen(urllib2.Request(the_url, headers = {'User-Agent': "Python-urllib/2.x (0rk/0.1.2)"})).read())

    return cached_img_file_path



if __name__ == "__main__":

    if len(sys.argv) == 1:
        print "You can learn about these subjects: %s" % ", ".join(SUBJECTS.keys())
        print "For example, to learn about the `man` command you can type: ./0rk man"
        raise SystemExit

    requested_subject = sys.argv[1]

    if SUBJECTS.has_key(requested_subject):
        if sys.platform == "darwin":
            image_file_path = get_cached_file_path(requested_subject)
            subprocess.call(["qlmanage", "-p", image_file_path], stdout=open(os.devnull, 'wb'))
        else:
            import webbrowser
            webbrowser.open(SUBJECTS[requested_subject]['page_url'], new=1)
    else:
        print "Sorry, that subject is not available."
        print "You could try `man %s`." % requested_subject
